version: "3.9"

services:
  ryot-theone:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    container_name: ryot-theone

  ryottheone:
    image: "git@github.com:workdojos/ryot.git"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-theone:5432/postgres
    ports:
      - "8020:8000"
    container_name: ryottheone

volumes:
  postgres_storage: