query LatestUserSummary {
  latestUserSummary {
    calculatedOn
    fitness {
      measurementsRecorded
      exercisesInteractedWith
      meditation {
        recorded
        duration
        weight
      }
     }
    media {
      metadataOverall {
        reviewed
        interactedWith
      }
      peopleOverall {
        reviewed
        interactedWith
      }
      comic {
        chapters
        read
      }
      books {
        pages
        read
      }
      movies {
        runtime
        watched
      }
      studies {
        episodes
        watched
      }
      podcasts {
        runtime
        played
        playedEpisodes
      }
      visualNovels {
        played
        runtime
      }
      videoGames {
        played
      }
      shows {
        runtime
        watchedEpisodes
        watchedSeasons
        watched
      }
      audioBooks {
        runtime
        played
      }
    }
  }
}
